"""add save_operations table

Revision ID: e378f7a1a884
Revises: 43da7a64a7ca
Create Date: 2026-09-14 13:56:05.432983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e378f7a1a884'
down_revision: Union[str, Sequence[str], None] = '43da7a64a7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('save_operations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('expected_revision', sa.BigInteger(), nullable=False),
    sa.Column('result_revision', sa.BigInteger(), nullable=True),
    sa.Column('failure_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('PROCESSING','SUCCEEDED','FAILED')", name='ck_save_operations_state'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'operation_id')
    )
    op.create_index(op.f('ix_save_operations_expires_at'), 'save_operations', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_save_operations_expires_at'), table_name='save_operations')
    op.drop_table('save_operations')
    # ### end Alembic commands ###
